// Checking with this to see if build succeeds
import { z } from 'zod'
import { insertProductSchema } from '@/lib/validators' // Adjust this path to where your schema lives

// 1. Infer the base properties from your Zod validator schema
export type InsertProduct = z.infer<typeof insertProductSchema>

// 2. Create the full Product type by combining the Zod schema with fields generated by Prisma
export type Product = Omit<InsertProduct, 'slug'> & {
  id: string
  slug: string | null
  rating: string
  createdAt: Date
}

// Brad's version
// import { insertProductSchema } from "@/lib/validators"
// import { z } from "zod"

// export type Product = z.infer<typeof insertProductSchema> & {
//   id: string,
//   slug: string | null,
//   rating: string,
//   createdAt: Date,
// }